# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeautyMaster' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BeautyMaster
  pod 'wax', :git=>'https://github.com/alibaba/wax.git'
  pod 'AVOSCloud'
  pod 'AVOSCloudIM'
  pod 'JPush'
  pod 'JAnalytics'

end
